services:

  postgres:
    image: postgres:15
    container_name: instagram-db
    environment:
      POSTGRES_DB: instagram
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  post-service:
    build: ./post-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  follow-service:
    build: ./follow-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres