POST http://localhost:8081/api/users/register
Content-Type: application/json

{
  "name": "Danilo",
  "username": "danilo4",
  "email": "danilo4@gmail.com",
  "password": "123456",
  "bio": "Hello",
  "profilePicture": "",
  "isPrivateProfile": false
}