POST http://localhost:8081/api/users/registe
Content-Type: application/json

{
  "name": "Danilo",
  "username": "danilo",
  "email": "danilo@gmail.com",
  "password": "123456",
  "bio": "Hello",
  "profilePicture": "",
  "private": false
}